"on":
  push:
    branches:
      - main
      - beta
name: Release
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - run: npm run build:schema
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.OCTOKITBOT_PAT }}
          NPM_TOKEN: ${{ secrets.OCTOKITBOT_NPM_TOKEN }}
